name: Build & test

on:
  push:
    branches:
      - main
      - leading
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    # Skip build if head commit contains 'skip ci'
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out
        uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run Android Lint
        run: ./gradlew lintDebug

      - name: Build with Gradle
        run:
          ./gradlew assembleDebug

  local-test:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 15

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Run Local Unit Test
        run: ./gradlew testDebug

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: Local-Test-Reports
          path: app/build/reports/tests/*
        if: always()

  android-emulator-test:
    runs-on: macos-latest
    needs: build
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        api-level: [ 29, 30 ]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      # setup JDK
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86
          profile: Galaxy Nexus
          script: ./gradlew connectedCheck --stacktrace

      # Upload results as a artifact even if the test failed
      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: Android-Test-Reports-API${{ matrix.api-level }}
          path: app/build/reports
        if: always()
